هذه البرامج مدعومة لنموذج التمويل

(ب)       :         إستعاعاضة عن ما يصل إلى 4 من المستحضرات التي تم تمكينها من خلال مثل،        [1,       المادة 2     ]
1 - الأبوة       :         إستعاعاضة عن (باتريون) واحد
مفتوح       :         إستعاعاضة عن مستعمل جمعي مفتوح واحد
ko_في       :         إستعاضة عن جهاز استخبارات من طراز كو-في
المدّل       :             :           :        استبدال بمبرة واحدة من طراز تيديلوفت/اسم الحزمة على سبيل المثال، npm/babel
المجتمع المحلي/جسر       :         إستعاعاضة عن مشروع جسر مجتمعي واحد على سبيل المثال، أسس السحاب
(ليبليباي)       :         إستعاضة عن مستعار واحد من أجل دفع الليبرالية
إصدار       :         إستعاضة عن قضية واحدة من طراز        "هنت"
(أوتشي)      :        إستعاضة عن مستعار واحد من أوتشي
(ج) تمويل الجمود      :           :         :       الاستعاضة عن اسم مشروع من طراز LFX (LFX) لتمويل مشروع تمويل، على سبيل المثال، أسس السحاب
عادة      :        يستعاض عن ما يصل إلى 4 رعاية العرف URLs e.g., ,  (1),  (2)]
